---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - sass
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.scss"
exclude_paths:
- config/
- db/
- spec/
- vendor/
